trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the Build"

- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo "Start DevDeploy"
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev

- stage: QADeploy
  jobs:
  - job: QaDeployJob
    steps:
    - bash: echo "Start QADeploy"
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA
